#!/bin/sh

echo -n "Starting Xorg... "
Xorg -noreset -br -deferglyphs 16 2>/dev/tty8 1>&2 vt07 &
xorg_pid=$!
echo "Done."
echo -n "Sleeping 1 secs... "
sleep 1
echo "Done."
export DISPLAY=:0
echo -n "Starting Setup Frontend... "
/usr/sbin/blinux-setup_step1
echo "Done."

kill ${xorg_pid}

echo "Exiting"

exit 0
 
